export interface Chain {
  id: string
  name: string
  symbol: string
  icon: string
  rpcUrl: string
  explorerUrl: string
  apiUrl?: string
  color: string
  testnet?: boolean
}

export interface ChainConfig {
  chains: Chain[]
}

import { getRpcUrl } from '../config/rpc'
import { FREE_API_ENDPOINTS } from '../config/rpc'

export const SUPPORTED_CHAINS: Chain[] = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    icon: '⟠',
    rpcUrl: getRpcUrl('ethereum', 0), // 使用免费 RPC
    explorerUrl: 'https://etherscan.io',
    apiUrl: FREE_API_ENDPOINTS.ethereum.url,
    color: 'from-blue-500 to-blue-700',
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    icon: '₿',
    rpcUrl: 'https://blockstream.info/api', // Blockstream 完全免费
    explorerUrl: 'https://blockstream.info',
    apiUrl: FREE_API_ENDPOINTS.bitcoin.url,
    color: 'from-orange-500 to-orange-700',
  },
  {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'MATIC',
    icon: '⬟',
    rpcUrl: getRpcUrl('polygon', 0),
    explorerUrl: 'https://polygonscan.com',
    apiUrl: FREE_API_ENDPOINTS.polygon.url,
    color: 'from-purple-500 to-purple-700',
  },
  {
    id: 'bsc',
    name: 'BNB Chain',
    symbol: 'BNB',
    icon: '🔶',
    rpcUrl: getRpcUrl('bsc', 0),
    explorerUrl: 'https://bscscan.com',
    apiUrl: FREE_API_ENDPOINTS.bsc.url,
    color: 'from-yellow-500 to-yellow-700',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    icon: '◎',
    rpcUrl: getRpcUrl('solana', 0),
    explorerUrl: 'https://solscan.io',
    apiUrl: FREE_API_ENDPOINTS.solana.url,
    color: 'from-green-500 to-green-700',
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    symbol: 'AVAX',
    icon: '🔺',
    rpcUrl: getRpcUrl('avalanche', 0),
    explorerUrl: 'https://snowtrace.io',
    apiUrl: FREE_API_ENDPOINTS.avalanche.url,
    color: 'from-red-500 to-red-700',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    symbol: 'ETH',
    icon: '🔷',
    rpcUrl: getRpcUrl('arbitrum', 0),
    explorerUrl: 'https://arbiscan.io',
    apiUrl: FREE_API_ENDPOINTS.arbitrum.url,
    color: 'from-cyan-500 to-cyan-700',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'ETH',
    icon: '🔵',
    rpcUrl: getRpcUrl('optimism', 0),
    explorerUrl: 'https://optimistic.etherscan.io',
    apiUrl: FREE_API_ENDPOINTS.optimism.url,
    color: 'from-pink-500 to-pink-700',
  },
  {
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    icon: '🔷',
    rpcUrl: getRpcUrl('base', 0),
    explorerUrl: 'https://basescan.org',
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: 'linea',
    name: 'Linea',
    symbol: 'ETH',
    icon: '📏',
    rpcUrl: getRpcUrl('linea', 0),
    explorerUrl: 'https://lineascan.build',
    color: 'from-indigo-500 to-indigo-700',
  },
  {
    id: 'zksync',
    name: 'zkSync Era',
    symbol: 'ETH',
    icon: '⚡',
    rpcUrl: getRpcUrl('zksync', 0),
    explorerUrl: 'https://explorer.zksync.io',
    color: 'from-violet-500 to-violet-700',
  },
  {
    id: 'scroll',
    name: 'Scroll',
    symbol: 'ETH',
    icon: '📜',
    rpcUrl: getRpcUrl('scroll', 0),
    explorerUrl: 'https://scrollscan.com',
    color: 'from-emerald-500 to-emerald-700',
  },
  {
    id: 'mantle',
    name: 'Mantle',
    symbol: 'MNT',
    icon: '🟢',
    rpcUrl: getRpcUrl('mantle', 0),
    explorerUrl: 'https://explorer.mantle.xyz',
    color: 'from-green-400 to-green-600',
  },
  {
    id: 'blast',
    name: 'Blast',
    symbol: 'ETH',
    icon: '💥',
    rpcUrl: getRpcUrl('blast', 0),
    explorerUrl: 'https://blastscan.io',
    color: 'from-yellow-400 to-yellow-600',
  },
  {
    id: 'starknet',
    name: 'Starknet',
    symbol: 'ETH',
    icon: '⭐',
    rpcUrl: getRpcUrl('starknet', 0),
    explorerUrl: 'https://starkscan.co',
    color: 'from-purple-400 to-purple-600',
  },
  {
    id: 'sui',
    name: 'Sui',
    symbol: 'SUI',
    icon: '💧',
    rpcUrl: getRpcUrl('sui', 0),
    explorerUrl: 'https://suiscan.xyz',
    color: 'from-cyan-400 to-cyan-600',
  },
  {
    id: 'aptos',
    name: 'Aptos',
    symbol: 'APT',
    icon: '🔄',
    rpcUrl: getRpcUrl('aptos', 0),
    explorerUrl: 'https://explorer.aptoslabs.com',
    color: 'from-blue-300 to-blue-500',
  },
  {
    id: 'tron',
    name: 'Tron',
    symbol: 'TRX',
    icon: '🔴',
    rpcUrl: getRpcUrl('tron', 0),
    explorerUrl: 'https://tronscan.org',
    color: 'from-red-500 to-red-700',
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    symbol: 'ATOM',
    icon: '🌌',
    rpcUrl: getRpcUrl('cosmos', 0),
    explorerUrl: 'https://www.mintscan.io/cosmos',
    color: 'from-indigo-400 to-indigo-600',
  },
  {
    id: 'near',
    name: 'NEAR',
    symbol: 'NEAR',
    icon: '🔵',
    rpcUrl: getRpcUrl('near', 0),
    explorerUrl: 'https://explorer.near.org',
    color: 'from-sky-400 to-sky-600',
  },
  {
    id: 'fantom',
    name: 'Fantom',
    symbol: 'FTM',
    icon: '👻',
    rpcUrl: getRpcUrl('fantom', 0),
    explorerUrl: 'https://ftmscan.com',
    color: 'from-blue-300 to-blue-500',
  },
  {
    id: 'celo',
    name: 'Celo',
    symbol: 'CELO',
    icon: '📱',
    rpcUrl: getRpcUrl('celo', 0),
    explorerUrl: 'https://explorer.celo.org',
    color: 'from-yellow-300 to-yellow-500',
  },
  {
    id: 'gnosis',
    name: 'Gnosis',
    symbol: 'GNO',
    icon: '🦉',
    rpcUrl: getRpcUrl('gnosis', 0),
    explorerUrl: 'https://gnosisscan.io',
    color: 'from-teal-400 to-teal-600',
  },
  {
    id: 'moonbeam',
    name: 'Moonbeam',
    symbol: 'GLMR',
    icon: '🌙',
    rpcUrl: getRpcUrl('moonbeam', 0),
    explorerUrl: 'https://moonscan.io',
    color: 'from-purple-300 to-purple-500',
  },
  {
    id: 'cronos',
    name: 'Cronos',
    symbol: 'CRO',
    icon: '⏰',
    rpcUrl: getRpcUrl('cronos', 0),
    explorerUrl: 'https://cronoscan.com',
    color: 'from-orange-400 to-orange-600',
  },
  {
    id: 'klaytn',
    name: 'Klaytn',
    symbol: 'KLAY',
    icon: '🔷',
    rpcUrl: getRpcUrl('klaytn', 0),
    explorerUrl: 'https://scope.klaytn.com',
    color: 'from-cyan-300 to-cyan-500',
  },
  {
    id: 'metis',
    name: 'Metis',
    symbol: 'METIS',
    icon: '🔷',
    rpcUrl: getRpcUrl('metis', 0),
    explorerUrl: 'https://andromeda-explorer.metis.io',
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: 'boba',
    name: 'Boba',
    symbol: 'ETH',
    icon: '🫧',
    rpcUrl: getRpcUrl('boba', 0),
    explorerUrl: 'https://bobascan.com',
    color: 'from-pink-300 to-pink-500',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    symbol: 'ETH',
    icon: '🌅',
    rpcUrl: getRpcUrl('aurora', 0),
    explorerUrl: 'https://explorer.aurora.dev',
    color: 'from-orange-300 to-orange-500',
  },
  {
    id: 'harmony',
    name: 'Harmony',
    symbol: 'ONE',
    icon: '🎵',
    rpcUrl: getRpcUrl('harmony', 0),
    explorerUrl: 'https://explorer.harmony.one',
    color: 'from-green-300 to-green-500',
  },
  {
    id: 'opbnb',
    name: 'opBNB',
    symbol: 'BNB',
    icon: '🔶',
    rpcUrl: getRpcUrl('opbnb', 0),
    explorerUrl: 'https://opbnbscan.com',
    color: 'from-yellow-400 to-yellow-600',
  },
  {
    id: 'zora',
    name: 'Zora',
    symbol: 'ETH',
    icon: '🎨',
    rpcUrl: getRpcUrl('zora', 0),
    explorerUrl: 'https://explorer.zora.energy',
    color: 'from-purple-400 to-purple-600',
  },
  {
    id: 'mode',
    name: 'Mode',
    symbol: 'ETH',
    icon: '🎯',
    rpcUrl: getRpcUrl('mode', 0),
    explorerUrl: 'https://explorer.mode.network',
    color: 'from-indigo-400 to-indigo-600',
  },
  {
    id: 'manta',
    name: 'Manta',
    symbol: 'ETH',
    icon: '🌊',
    rpcUrl: getRpcUrl('manta', 0),
    explorerUrl: 'https://pacific-explorer.manta.network',
    color: 'from-blue-300 to-blue-500',
  },
]

export type SearchType = 'address' | 'transaction' | 'block' | 'token' | 'nft'

export interface SearchResult {
  type: SearchType
  chain: string
  data: any
}
